"""empty message

Revision ID: 074ab41f4aa2
Revises: d718184e7b5a
Create Date: 2025-08-27 02:00:50.344375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074ab41f4aa2'
down_revision = 'd718184e7b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('StartDate', sa.DateTime(), nullable=False),
    sa.Column('CompletedDate', sa.DateTime(), nullable=True),
    sa.Column('Deadline', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
