"""empty message

Revision ID: 4c058cabc4ff
Revises: 074ab41f4aa2
Create Date: 2025-08-27 04:14:56.818151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c058cabc4ff'
down_revision = '074ab41f4aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('EndDate', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('EndDate')

    # ### end Alembic commands ###
